services:
  - type: web
    name: trustlens-backend
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT
        sync: false
      - key: AZURE_OPENAI_API_VERSION
        sync: false
      - key: AZURE_VISION_KEY
        sync: false
      - key: AZURE_VISION_ENDPOINT
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ./google-credentials.json
