"""
TrustLens Phase 4: Image Authenticity Service Tests

All tests are fully offline — no network, no OS-level image loading beyond
in-memory synthetic pixel data generated by Pillow.

Run:
    python3 -m unittest tests.test_image_authenticity -v
"""

import io
import unittest
from unittest.mock import patch, MagicMock

from PIL import Image

from app.utils.image_utils import is_valid_image, bytes_to_pil, get_image_format
from app.utils.hash_utils import compute_phash, phash_distance, is_similar
from app.utils.metadata_utils import extract_exif
from app.services.image_authenticity_service import (
    evaluate_image,
    _detect_context_mismatch,
    _compute_score,
    BASELINE_SCORE,
    REUSE_PENALTY,
    MISMATCH_PENALTY,
    MISSING_METADATA_PENALTY,
    EDITING_SOFTWARE_PENALTY,
    AI_PROBABILITY_PENALTY,
    AI_HIGH_THRESHOLD,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_image_bytes(width: int = 100, height: int = 100, color: str = "red") -> bytes:
    """Create a minimal in-memory JPEG for testing."""
    buf = io.BytesIO()
    Image.new("RGB", (width, height), color=color).save(buf, format="JPEG")
    return buf.getvalue()


def _make_png_bytes() -> bytes:
    buf = io.BytesIO()
    Image.new("RGB", (50, 50), color="blue").save(buf, format="PNG")
    return buf.getvalue()


# ---------------------------------------------------------------------------
# Part 1 — image_utils.py
# ---------------------------------------------------------------------------

class TestImageUtils(unittest.TestCase):

    def test_valid_jpeg_returns_true(self):
        self.assertTrue(is_valid_image(_make_image_bytes()))

    def test_valid_png_returns_true(self):
        self.assertTrue(is_valid_image(_make_png_bytes()))

    def test_empty_bytes_invalid(self):
        self.assertFalse(is_valid_image(b""))

    def test_none_invalid(self):
        self.assertFalse(is_valid_image(None))

    def test_corrupt_bytes_invalid(self):
        self.assertFalse(is_valid_image(b"notanimage" * 10))

    def test_bytes_to_pil_valid(self):
        img = bytes_to_pil(_make_image_bytes())
        self.assertIsNotNone(img)
        self.assertIsInstance(img, Image.Image)

    def test_bytes_to_pil_invalid_returns_none(self):
        self.assertIsNone(bytes_to_pil(b"garbage"))

    def test_bytes_to_pil_none_input(self):
        self.assertIsNone(bytes_to_pil(None))

    def test_get_image_format_jpeg(self):
        fmt = get_image_format(_make_image_bytes())
        self.assertEqual(fmt, "JPEG")

    def test_get_image_format_png(self):
        fmt = get_image_format(_make_png_bytes())
        self.assertEqual(fmt, "PNG")

    def test_too_large_image_rejected(self):
        from app.utils.image_utils import MAX_IMAGE_BYTES
        oversized = b"x" * (MAX_IMAGE_BYTES + 1)
        self.assertIsNone(bytes_to_pil(oversized))


# ---------------------------------------------------------------------------
# Part 2 — hash_utils.py
# ---------------------------------------------------------------------------

class TestHashUtils(unittest.TestCase):

    def test_compute_phash_valid_image(self):
        result = compute_phash(_make_image_bytes())
        self.assertIsNotNone(result)
        self.assertIsInstance(result, str)
        self.assertEqual(len(result), 16)  # imagehash pHash default hex length

    def test_compute_phash_none_input(self):
        self.assertIsNone(compute_phash(None))

    def test_compute_phash_empty_bytes(self):
        self.assertIsNone(compute_phash(b""))

    def test_compute_phash_corrupt_bytes(self):
        self.assertIsNone(compute_phash(b"notanimage"))

    def test_identical_images_have_zero_distance(self):
        img_bytes = _make_image_bytes(color="green")
        h1 = compute_phash(img_bytes)
        h2 = compute_phash(img_bytes)
        self.assertEqual(phash_distance(h1, h2), 0)

    def test_different_images_have_nonzero_distance(self):
        h1 = compute_phash(_make_image_bytes(color="red"))
        h2 = compute_phash(_make_image_bytes(color="blue"))
        dist = phash_distance(h1, h2)
        self.assertIsNotNone(dist)
        # Different solid colours — distance typically > 0
        # (solid colour images may still have similar DCT, so just check not None)
        self.assertGreaterEqual(dist, 0)

    def test_phash_distance_none_inputs(self):
        self.assertIsNone(phash_distance(None, None))
        self.assertIsNone(phash_distance("abc", None))
        self.assertIsNone(phash_distance(None, "abc"))

    def test_is_similar_identical_hashes(self):
        img = _make_image_bytes(color="yellow")
        h = compute_phash(img)
        self.assertTrue(is_similar(h, h))

    def test_is_similar_with_none_returns_false(self):
        self.assertFalse(is_similar(None, None))
        self.assertFalse(is_similar("abc123", None))

    def test_is_similar_threshold_respected(self):
        img = _make_image_bytes(color="red")
        h = compute_phash(img)
        # Same hash — distance = 0 — always similar regardless of threshold
        self.assertTrue(is_similar(h, h, threshold=0))


# ---------------------------------------------------------------------------
# Part 3 — metadata_utils.py
# ---------------------------------------------------------------------------

class TestMetadataUtils(unittest.TestCase):

    def test_jpeg_without_exif_returns_not_present(self):
        img_bytes = _make_image_bytes()  # synthetic JPEG has no EXIF
        result = extract_exif(img_bytes)
        self.assertFalse(result["metadataPresent"])
        self.assertEqual(result["rawTagCount"], 0)

    def test_empty_bytes_returns_default(self):
        result = extract_exif(b"")
        self.assertFalse(result["metadataPresent"])

    def test_none_input_returns_default(self):
        result = extract_exif(None)
        self.assertFalse(result["metadataPresent"])

    def test_corrupt_bytes_returns_default(self):
        result = extract_exif(b"corruptdata")
        self.assertFalse(result["metadataPresent"])

    def test_png_returns_no_metadata(self):
        result = extract_exif(_make_png_bytes())
        self.assertFalse(result["metadataPresent"])  # PNG has no _getexif()

    def test_editing_software_detected_flag(self):
        """Mock _getexif to simulate Photoshop in EXIF Software tag."""
        fake_exif = {
            305: "Adobe Photoshop CS6",  # 305 = Software tag
            271: "Canon",                # 271 = Make
            272: "EOS 5D",              # 272 = Model
        }
        mock_img = MagicMock()
        mock_img._getexif.return_value = fake_exif

        with patch("PIL.Image.open", return_value=mock_img):
            result = extract_exif(_make_image_bytes())

        self.assertTrue(result["editingSoftwareDetected"])
        self.assertIn("photoshop", result["software"].lower())

    def test_clean_camera_software_not_flagged(self):
        fake_exif = {
            305: "Canon EOS Firmware 1.0",
            271: "Canon",
        }
        mock_img = MagicMock()
        mock_img._getexif.return_value = fake_exif

        with patch("PIL.Image.open", return_value=mock_img):
            result = extract_exif(_make_image_bytes())

        self.assertFalse(result["editingSoftwareDetected"])

    def test_output_has_all_required_keys(self):
        result = extract_exif(_make_image_bytes())
        for key in ["metadataPresent", "cameraMake", "cameraModel", "software",
                    "dateTimeOriginal", "gpsPresent", "editingSoftwareDetected", "rawTagCount"]:
            self.assertIn(key, result)


# ---------------------------------------------------------------------------
# Part 4 — Context mismatch detection
# ---------------------------------------------------------------------------

class TestContextMismatch(unittest.TestCase):

    def test_matching_context_returns_false(self):
        """Same event tokens → no mismatch."""
        stored = "Flood in Kerala India 2019"
        claim = "The 2019 Kerala flood devastated the state"
        self.assertFalse(_detect_context_mismatch(stored, claim))

    def test_different_context_returns_true(self):
        """Completely different topic → mismatch."""
        stored = "Flood in Kerala India 2019"
        claim = "Russia Ukraine military operation 2022"
        self.assertTrue(_detect_context_mismatch(stored, claim))

    def test_empty_claim_returns_false(self):
        """Cannot assess mismatch without claim context."""
        self.assertFalse(_detect_context_mismatch("Flood in Kerala", ""))
        self.assertFalse(_detect_context_mismatch("Flood in Kerala", None))

    def test_short_claim_returns_false(self):
        """Claim shorter than MIN_CONTEXT_LENGTH → returns False safely."""
        self.assertFalse(_detect_context_mismatch("Flood in Kerala", "fire"))


# ---------------------------------------------------------------------------
# Part 5 — Score normalisation
# ---------------------------------------------------------------------------

class TestComputeScore(unittest.TestCase):

    def test_no_signals_returns_baseline(self):
        score, factors = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=0.0,
        )
        self.assertEqual(score, BASELINE_SCORE)
        self.assertEqual(factors, [])

    def test_reuse_penalty_applied(self):
        score, factors = _compute_score(
            hash_matched=True,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=0.0,
        )
        self.assertEqual(score, BASELINE_SCORE - REUSE_PENALTY)
        self.assertTrue(any("known photograph" in f or "previously used" in f for f in factors))

    def test_context_mismatch_penalty_applied(self):
        score, factors = _compute_score(
            hash_matched=True,
            context_mismatch=True,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=0.0,
        )
        self.assertEqual(score, BASELINE_SCORE - REUSE_PENALTY - MISMATCH_PENALTY)
        self.assertTrue(any("mismatch" in f.lower() for f in factors))

    def test_missing_metadata_penalty(self):
        score, factors = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=False,
            editing_software_detected=False,
            ai_probability=0.0,
        )
        self.assertEqual(score, BASELINE_SCORE - MISSING_METADATA_PENALTY)

    def test_editing_software_penalty(self):
        score, _ = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=True,
            ai_probability=0.0,
        )
        self.assertEqual(score, BASELINE_SCORE - EDITING_SOFTWARE_PENALTY)

    def test_high_ai_probability_penalty(self):
        score, factors = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=AI_HIGH_THRESHOLD + 0.1,
        )
        self.assertEqual(score, BASELINE_SCORE - AI_PROBABILITY_PENALTY)
        self.assertTrue(any("AI" in f for f in factors))

    def test_low_ai_probability_no_penalty(self):
        score, _ = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=0.3,
        )
        self.assertEqual(score, BASELINE_SCORE)

    def test_all_penalties_clamped_to_zero(self):
        """All penalties combined must not go below 0."""
        score, _ = _compute_score(
            hash_matched=True,
            context_mismatch=True,
            metadata_present=False,
            editing_software_detected=True,
            ai_probability=0.9,
        )
        self.assertGreaterEqual(score, 0)

    def test_score_never_exceeds_100(self):
        score, _ = _compute_score(
            hash_matched=False,
            context_mismatch=False,
            metadata_present=True,
            editing_software_detected=False,
            ai_probability=0.0,
        )
        self.assertLessEqual(score, 100)


# ---------------------------------------------------------------------------
# Part 6 — evaluate_image integration
# ---------------------------------------------------------------------------

class TestEvaluateImage(unittest.TestCase):

    def test_none_input_returns_neutral(self):
        result = evaluate_image(None)
        self.assertEqual(result["imageAuthenticityScore"], BASELINE_SCORE)
        self.assertFalse(result["hashMatched"])

    def test_empty_bytes_returns_neutral(self):
        result = evaluate_image(b"")
        self.assertEqual(result["imageAuthenticityScore"], BASELINE_SCORE)

    def test_corrupt_bytes_returns_neutral(self):
        result = evaluate_image(b"notanimage" * 5)
        self.assertEqual(result["imageAuthenticityScore"], BASELINE_SCORE)
        self.assertTrue(len(result["riskFactors"]) > 0)

    def test_valid_image_no_hash_match_returns_score(self):
        with patch("app.services.image_authenticity_service.lookup_hash", return_value=None):
            result = evaluate_image(_make_image_bytes(), claim_context=None)
        self.assertIsNotNone(result["imageAuthenticityScore"])
        self.assertFalse(result["hashMatched"])

    def test_hash_match_applies_reuse_penalty(self):
        mock_entry = {
            "hash": "abc", "context": "Flood in Kerala 2019",
            "verifiedEventDate": "2019-08-12", "source": "The Hindu",
        }
        with patch("app.services.image_authenticity_service.lookup_hash", return_value=mock_entry):
            result = evaluate_image(
                _make_image_bytes(),
                claim_context="Russia Ukraine war 2022",   # clear mismatch
            )
        self.assertTrue(result["hashMatched"])
        self.assertEqual(result["matchedContext"], "Flood in Kerala 2019")
        self.assertLess(result["imageAuthenticityScore"], BASELINE_SCORE)

    def test_hash_match_same_context_no_mismatch(self):
        mock_entry = {
            "hash": "abc", "context": "Flood in Kerala 2019",
            "verifiedEventDate": "2019-08-12", "source": "The Hindu",
        }
        with patch("app.services.image_authenticity_service.lookup_hash", return_value=mock_entry):
            result = evaluate_image(
                _make_image_bytes(),
                claim_context="Kerala flood 2019 rescue operations",  # matches
            )
        self.assertTrue(result["hashMatched"])
        self.assertFalse(result["contextMismatch"])

    def test_output_structure_always_complete(self):
        """All required keys must be present on any input."""
        result = evaluate_image(_make_image_bytes())
        required = [
            "imageAuthenticityScore", "hashMatched", "matchedContext",
            "matchedEventDate", "contextMismatch", "aiGeneratedLikelihood",
            "metadataPresent", "cameraMake", "cameraModel",
            "editingSoftwareDetected", "riskFactors",
        ]
        for key in required:
            self.assertIn(key, result, f"Missing key: {key}")

    def test_unhandled_exception_returns_neutral(self):
        """evaluate_image must never raise — even on unexpected errors."""
        with patch("app.services.image_authenticity_service.is_valid_image", return_value=True), \
             patch("app.services.image_authenticity_service.compute_phash",
                   side_effect=RuntimeError("unexpected")):
            result = evaluate_image(_make_image_bytes())
        # Should get neutral score without crashing
        self.assertEqual(result["imageAuthenticityScore"], BASELINE_SCORE)


if __name__ == "__main__":
    unittest.main()
