"""
TrustLens Analyze Route (Phase 6 async refactor)

Flask 2.0+ supports async route handlers natively.
Hypercorn (ASGI) is required to honour the async semantics — the default
Werkzeug dev server is WSGI-only and would run the coroutine synchronously,
eliminating all concurrency gains.

Key changes from the synchronous version:
  1. `async def analyze()` — Flask detects the coroutine and schedules it properly
  2. `await download_image()` — single download replacing the previous double-call
  3. `await analyze_text_with_llm()` — no longer blocks the event loop
  4. `await compute_full_credibility()` — internally uses asyncio.gather for
     phases 2, 3, 4 concurrently
"""

import asyncio
import time
import re
import traceback
import json
from typing import Any
from flask import Blueprint, request, jsonify
from pydantic import ValidationError
from app.models.schemas import AnalyzeRequest
from app.services.llm_analysis import analyze_text_with_llm, analyze_image_with_llm
from app.services.credibility_engine import compute_full_credibility
from app.services.image_metadata import analyze_image_metadata
from app.services.image_tracing import trace_image
from app.services.image_scoring import calculate_image_credibility
from app.services.analysis_storage_service import store_analysis, get_analysis_by_hash
from app.utils.fetch_image import download_image
from app.utils.hashing import hash_image, hash_text
from app.services.video_analysis import analyze_video_with_llm
from app.services.video.video_pipeline import process_video_text
from app.services.evidence_pipeline.pipeline import run_evidence_pipeline
from app.services import job_registry
from app.utils.text_utils import normalize_claim_text
from app.services.claim_memory_service import find_similar_claim, store_claim_result
from app.services.narrative_engine import process_narratives
from app.services.response_builder import build_analysis_response

import logging

logger = logging.getLogger(__name__)

analyze_bp = Blueprint('analyze', __name__)

VALID_VERDICTS = ["Highly Reliable", "Reliable", "Likely Reliable", "Questionable", "High Risk"]
VERDICT_MAP = {v.lower(): v for v in VALID_VERDICTS}


def normalize_verdict(verdict: Any) -> str:
    if isinstance(verdict, str):
        # Handle snake_case or SCREAMING_SNAKE_CASE from agents
        normalized = verdict.replace("_", " ").lower()
        if normalized in VERDICT_MAP:
            return VERDICT_MAP[normalized]
        # Map common variations
        if "likely" in normalized and "reliable" in normalized:
            return "Likely Reliable"
        if "medium" in normalized or "risk" in normalized:
            return "Questionable" if "medium" in normalized else "High Risk"
            
    return "High Risk"


# ---------------------------------------------------------------------------
# Cancel endpoint — called by the extension when the user dismisses the overlay
# ---------------------------------------------------------------------------
@analyze_bp.route('/cancel', methods=['POST'])
def cancel_analysis():
    """
    Cancel an in-flight analysis task identified by jobId.
    The jobId is generated by the extension client and sent with the
    original /api/analyze request.
    """
    data = request.get_json(silent=True) or {}
    job_id = data.get('jobId', '')
    if not job_id:
        return jsonify({"cancelled": False, "error": "Missing jobId"}), 400

    cancelled = job_registry.cancel(job_id)
    print(f"{'🛑' if cancelled else '⏭️'} [Cancel] job={job_id} cancelled={cancelled}")
    return jsonify({"cancelled": cancelled})


@analyze_bp.route('', methods=['GET'])
def get_analyze_info():
    return jsonify({
        "success": True,
        "message": "TrustLens Analyze API",
        "endpoint": "/api/analyze",
        "method": "POST",
        "description": "Analyze text and images for misinformation risk assessment",
        "requestBody": {
            "text": {"type": "string", "required": False, "minLength": 5},
            "imageUrl": {"type": "string", "required": False, "format": "url"},
        },
        "example": {
            "text": "This is a sample text to analyze for misinformation",
            "imageUrl": "https://example.com/image.jpg",
        },
    })


@analyze_bp.route('', methods=['POST'])
async def analyze():
    """
    Async POST handler — Flask 2.0+ schedules this as a coroutine.
    Requires Hypercorn (ASGI) to run concurrently.
    """
    _start = time.perf_counter()
    job_id: str | None = None
    all_claims_data = []  # List of {"text": "...", "source": "..."}

    try:
        print("📥 /api/analyze route hit")

        data = request.get_json()
        if not data:
            return jsonify({"success": False, "message": "Invalid JSON in request body"}), 400

        # Create a unique hash for the entire request payload to support full-request caching
        request_hash = hash_text(json.dumps(data, sort_keys=True))
        existing_full_analysis = get_analysis_by_hash(request_hash)
        
        if existing_full_analysis:
            print(f"♻️ Reusing full cached analysis for request hash: {request_hash[:16]}...")
            cached_response = existing_full_analysis.get("analysis", {})
            cached_response["reused"] = True
            cached_response["cachedAt"] = existing_full_analysis.get("createdAt")
            return jsonify(cached_response)

        # Register this asyncio Task so the /cancel endpoint can stop it.
        job_id = data.get("jobId") or ""
        if job_id:
            current_task = asyncio.current_task()
            if current_task:
                job_registry.register(job_id, current_task)
                print(f"📋 [Job] Registered analysis task: {job_id}")

        try:
            validated_data = AnalyzeRequest(**data)
        except ValidationError as e:
            return jsonify({"success": False, "message": e.errors()[0]['msg']}), 400


        # ------------------------------------------------------------------ #
        # Step 1: Image download
        # ------------------------------------------------------------------ #
        image_buffer: bytes | None = None
        image_hash: str | None = None
        image_reused = False
        image_analysis: dict = {"status": "skipped"}

        if validated_data.imageUrl:
            try:
                print(f"🖼️ Fetching image: {validated_data.imageUrl}")
                dl = await download_image(validated_data.imageUrl)

                if dl.get("success") and dl.get("buffer"):
                    image_buffer = dl["buffer"]
                    image_hash = hash_image(image_buffer)
                    existing_image = get_analysis_by_hash(image_hash)

                    if existing_image:
                        print(f"♻️ Reusing cached image analysis for hash: {image_hash[:16]}...")
                        image_analysis = existing_image.get("analysis", {})
                        image_analysis["reused"] = True
                        image_reused = True
                    else:
                        metadata, tracing, llm_image_container = {}, {}, {}
                        try:
                            metadata = analyze_image_metadata(image_buffer)
                            tracing  = trace_image(image_buffer)
                        except Exception as tech_err:
                            print(f"⚠️ Technical analysis error: {tech_err}")

                        try:
                            print("🎨 Starting LLM Image Analysis...")
                            llm_image_container = await analyze_image_with_llm(image_buffer, validated_data.text or "")
                            print(f"✅ LLM Image Analysis done")
                            llm_image_result = llm_image_container.get("analysis", {})
                        except Exception as llm_err:
                            print(f"❌ LLM image analysis failed: {llm_err}")
                            llm_image_result = {}

                        ai_prob = llm_image_result.get("aiGeneratedProbability", 0)
                        credibility_result = calculate_image_credibility(metadata, tracing, ai_prob)
                        llm_score   = int(llm_image_result.get("credibilityScore", 100))
                        tech_score  = int(credibility_result.get("score", 100))
                        final_image_score = min(llm_score, tech_score)

                        final_image_verdict = normalize_verdict(
                            llm_image_result.get("verdict", credibility_result.get("verdict", "High Risk"))
                        )
                        if final_image_score < 40:
                            final_image_verdict = "High Risk"
                        elif final_image_score < 75:
                            final_image_verdict = "Questionable"

                        image_analysis = {
                            "status": "processed",
                            "metadata": metadata,
                            "tracing":  tracing,
                            "llmAnalysis": {
                                "riskLevel":              llm_image_result.get("riskLevel", "medium"),
                                "verdict":                normalize_verdict(llm_image_result.get("verdict")),
                                "credibilityScore":       llm_image_result.get("credibilityScore", 50),
                                "extractedText":          llm_image_result.get("extractedText", ""),
                                "textVerification":       llm_image_result.get("textVerification", ""),
                                "claims":                 llm_image_result.get("claims", []),
                                "imageContent":           llm_image_result.get("imageContent", ""),
                                "conveyedMessage":        llm_image_result.get("conveyedMessage", ""),
                                "veracityCheck":          llm_image_result.get("veracityCheck", ""),
                                "explanation":            llm_image_result.get("explanation", ""),
                                "visualRedFlags":         llm_image_result.get("visualRedFlags", []),
                                "aiGeneratedProbability": llm_image_result.get("aiGeneratedProbability", 0),
                                "mediaExplanation":       llm_image_result.get("mediaExplanation", ""),
                                "aiReasoning":            llm_image_result.get("aiReasoning", ""),
                            } if llm_image_result else None,
                            "credibilityScore": final_image_score,
                            "verdict":          final_image_verdict,
                        }
                        
                        # Add image claims to unified pipeline
                        image_claims = llm_image_container.get("claims", [])
                        if image_claims:
                            for c in image_claims:
                                all_claims_data.append({
                                    "text": str(c), 
                                    "source": "image",
                                    "media_context": {
                                        "text_present": bool(validated_data.text),
                                        "image_present": bool(validated_data.imageUrl),
                                        "video_present": bool(validated_data.videoUrl)
                                    }
                                })
                                
                        store_analysis(image_hash, "image", image_analysis)
                else:
                    print(f"⚠️ Image download failed: {dl.get('error')}")
                    image_analysis = {"status": "skipped", "error": dl.get("error")}

            except Exception as e:
                print(f"❌ [Image Analysis] Unexpected error: {e}")
                image_analysis = {"status": "skipped", "error": str(e)}

        # ------------------------------------------------------------------ #
        # Step 2: Text analysis
        # ------------------------------------------------------------------ #
        text_hash: str | None = None
        text_reused = False
        text_analysis: dict = {"status": "skipped"}

        if validated_data.text:
            text_hash = hash_text(validated_data.text)
            existing_text = get_analysis_by_hash(text_hash)

            if existing_text:
                print(f"♻️ Reusing cached text analysis for hash: {text_hash[:16]}...")
                text_analysis = existing_text.get("analysis", {})
                text_reused = True
            else:
                try:
                    print("✍️ Starting LLM Text Analysis...")
                    llm_text_container = await analyze_text_with_llm(validated_data.text)
                    print("✅ LLM Text Analysis complete")

                    llm_result = llm_text_container.get("analysis", {})
                    semantic_score = llm_result.get("semanticScore", 50)
                    credibility_score = max(0, min(100, int(semantic_score)))
                    
                    if credibility_score >= 75:
                        verdict, risk_level = "Reliable", "low"
                    elif credibility_score >= 40:
                        verdict, risk_level = "Questionable", "medium"
                    else:
                        verdict, risk_level = "High Risk", "high"

                    risk_keywords = list(
                        llm_result.get("manipulationIndicators", [])
                        + llm_result.get("riskFactors", [])
                    )[:20]

                    # --- Claim Validation & Normalisation ---
                    validated_claims = llm_text_container.get("claims", [])

                    text_analysis = {
                        "credibilityScore":  credibility_score,
                        "verdict":           normalize_verdict(verdict),
                        "riskLevel":         risk_level,
                        "riskKeywordsFound": risk_keywords,
                        "keyClaims":         validated_claims,
                        "validatedClaims":   validated_claims,
                        "explanation":       llm_result.get("reasoningSummary", ""),
                        "scoreReasoning":    llm_result.get("scoreReasoning", llm_result.get("reasoningSummary", "")),
                        "semantic": {
                            "semanticScore":          llm_result.get("semanticScore"),
                            "confidenceScore":        llm_result.get("confidenceScore"),
                            "primaryClaim":           llm_result.get("primaryClaim"),
                            "keyClaims":              validated_claims,
                            "manipulationIndicators": llm_result.get("manipulationIndicators", []),
                            "riskFactors":            llm_result.get("riskFactors", []),
                            "evidenceStrength":       llm_result.get("evidenceStrength"),
                            "reasoningSummary":       llm_result.get("reasoningSummary"),
                        },
                    }

                    # --- Collect claims for unified pipeline ---
                    if validated_claims:
                        for c in validated_claims:
                            all_claims_data.append({
                                "text": str(c), 
                                "source": "text",
                                "media_context": {
                                    "text_present": bool(validated_data.text),
                                    "image_present": bool(validated_data.imageUrl),
                                    "video_present": bool(validated_data.videoUrl)
                                }
                            })

                    # --- Empty-claims fallback ---
                    if not validated_claims:
                        print("⚠️ No valid claims found after filtering — applying empty-claim fallback")
                        text_analysis["noVerifiableClaims"] = True
                        text_analysis["explanation"] = (
                            "No verifiable factual claims were identified in the content. "
                            + text_analysis.get("explanation", "")
                        ).strip()
                        text_analysis["credibilityScore"] = min(credibility_score, 40)
                        text_analysis["semantic"]["evidenceStrength"] = "Weak"

                    store_analysis(text_hash, "text", text_analysis)

                except Exception as e:
                    logger.error(f"❌ LLM text analysis failed: {e}")
                    text_analysis = {"status": "skipped", "error": f"LLM text analysis failed: {e}"}
        else:
            print("📝 No text provided, skipping LLM text analysis")

        # ------------------------------------------------------------------ #
        # Step 2.5: Video Analysis
        # ------------------------------------------------------------------ #
        video_analysis: dict = {"status": "skipped"}
        video_hash: str | None = None
        video_reused = False

        if validated_data.videoUrl:
            video_hash = hash_text(validated_data.videoUrl)
            existing_video = get_analysis_by_hash(video_hash)

            if existing_video:
                print(f"♻️ Reusing cached video analysis...")
                video_analysis = existing_video.get("analysis", {})
                video_reused = True
            else:
                try:
                    # Sanity check
                    valid_post_patterns = [
                        r"/status/", r"/reels?/", r"/video/", r"/p/", r"/watch", 
                        r"/shorts/", r"/v/", r"/clip/"
                    ]
                    
                    is_valid_post = any(re.search(pattern, validated_data.videoUrl.lower()) for pattern in valid_post_patterns)
                    
                    if not is_valid_post:
                        print(f"⏩ Skipping video extraction: URL '{validated_data.videoUrl}' does not look like a specific video post")
                        video_analysis = {"status": "skipped", "error": "Not a valid video post URL"}
                    else:
                        print(f"📹 Starting multimodal video extraction for: {validated_data.videoUrl}")
                        extraction_result = await process_video_text(validated_data.videoUrl)
    
                        if extraction_result.get("success"):
                            print(f"🤖 Starting LLM video analysis against Multimodal String...")
                            llm_video_container = await asyncio.to_thread(
                                analyze_video_with_llm,
                                extraction_result.get("combinedVideoText", ""),
                                validated_data.videoUrl,
                                validated_data.text or ""
                            )
                            llm_video_result = llm_video_container.get("analysis", {})
                            
                            # --- Collect video claims for unified pipeline ---
                            video_claims = llm_video_container.get("claims", [])
                            if video_claims:
                                for c in video_claims:
                                    all_claims_data.append({
                                        "text": str(c), 
                                        "source": "video",
                                        "media_context": {
                                            "text_present": bool(validated_data.text),
                                            "image_present": bool(validated_data.imageUrl),
                                            "video_present": bool(validated_data.videoUrl)
                                        }
                                    })

                            video_analysis = {
                                "status": "processed",
                                "platform": extraction_result.get("platform"),
                                "credibilityScore": llm_video_result.get("credibilityScore", 50),
                                "verdict": normalize_verdict(llm_video_result.get("verdict", "Questionable")),
                                "riskLevel": llm_video_result.get("riskLevel", "medium"),
                                "explanation": llm_video_result.get("explanation", ""),
                                "topicSummary": llm_video_result.get("topicSummary", ""),
                                "visualSummary": llm_video_container.get("visualSummary", ""),
                                "framesAnalyzed": extraction_result.get("framesAnalyzed", 0),
                                "visualTextDetected": extraction_result.get("visualTextDetected", False),
                                "ocrText": extraction_result.get("ocrText", []),
                                "validatedClaims": video_claims,
                                "aiDetection": extraction_result.get("aiDetection", {}),
                                "contextDetection": extraction_result.get("contextDetection", {}),
                                "llmAnalysis": {
                                    "riskKeywordsFound": llm_video_result.get("riskKeywordsFound", []),
                                    "claims": video_claims,
                                }
                            }
                            
                            store_analysis(video_hash, "video", video_analysis)
                        else:
                            print(f"⚠️ Video extraction failed: {extraction_result.get('error')}")
                            video_analysis = {"status": "skipped", "error": extraction_result.get("error")}
                except Exception as e:
                    print(f"❌ Video analysis failed: {e}")
                    video_analysis = {"status": "skipped", "error": str(e)}

        # ------------------------------------------------------------------ #
        # Step 3: Unified Evidence Pipeline — with Claim Memory (Part-13)    #
        # ------------------------------------------------------------------ #
        # Pipeline Order: Entity Extraction → Normalization → Validation → Query Gen
        from app.services.claim_validator import is_valid_claim
        from app.services.evidence_pipeline.entity_extraction import extract_entities

        seen_claims = set()
        deduped_claims = []
        for c in all_claims_data:
            # 1. Entity Extraction on RAW claim
            entities = extract_entities(c["text"])
            logger.debug(f"Entities detected: {entities}")

            # 2. Normalization
            clean_text = normalize_claim_text(c["text"])
            logger.debug(f"Claim normalized: '{clean_text}'")

            if clean_text not in seen_claims:
                # 3. Validation
                if is_valid_claim(clean_text):
                    seen_claims.add(clean_text)
                    c["normalized_text"] = clean_text
                    c["entities"] = entities
                    deduped_claims.append(c)
                    logger.debug(f"Claim normalization & validation passed: '{c['text']}' -> '{clean_text}'")
                else:
                    logger.debug(f"Claim validation failed, dropping: '{c['text']}'")

        evidence_results = []
        if deduped_claims:
            print(f"📡 Running unified evidence pipeline on {len(deduped_claims)} claims...")

            # --- Memory lookup: check each claim before running the pipeline ---
            verified_from_memory = []
            claims_to_verify = []

            for claim_item in deduped_claims:
                mem_result = find_similar_claim(claim_item["text"])
                if mem_result:
                    logger.info(f"[Memory] ♻️  Reusing cached verification for: '{claim_item['text'][:60]}'")
                    # Patch claim/source back from the original item
                    mem_result["claim"]  = claim_item["text"]
                    mem_result["source"] = claim_item.get("source", "memory")
                    verified_from_memory.append(mem_result)
                else:
                    logger.info(f"[Memory] 🔍 Cache miss — will verify: '{claim_item['text'][:60]}'")
                    claims_to_verify.append(claim_item)

            # --- Run pipeline only for cache misses ---
            if claims_to_verify:
                pipeline_results = await run_evidence_pipeline(claims_to_verify, request_id=job_id)
            else:
                pipeline_results = []

            # --- Store high-quality new results in memory ---
            stored_count = 0
            for res in pipeline_results:
                if store_claim_result(
                    res.get("claim", ""),
                    res.get("verification", {}),
                    res.get("stats", {}),
                ):
                    stored_count += 1

            if stored_count:
                logger.info(f"[Memory] 💾 Stored {stored_count} new verified claims")

            # --- Merge memory hits + pipeline results ---
            evidence_results = verified_from_memory + pipeline_results

            mem_hits = len(verified_from_memory)
            print(
                f"✅ Unified evidence pipeline complete: {len(evidence_results)} verified "
                f"({mem_hits} from memory, {len(pipeline_results)} fresh)"
            )

        # ------------------------------------------------------------------ #
        # Step 3.5: Narrative Intelligence Engine (Part-13)                   #
        # ------------------------------------------------------------------ #
        narrative_summaries = []
        if evidence_results:
            try:
                narrative_summaries = await process_narratives(evidence_results)
                logger.info(
                    f"[NarrativeEngine] Processed {len(narrative_summaries)} claim(s) "
                    f"through narrative engine"
                )
            except Exception as _ne_err:
                logger.warning(f"[NarrativeEngine] Non-fatal error: {_ne_err}")
                narrative_summaries = []


        # ------------------------------------------------------------------ #
        # Step 4: Final scoring
        # ------------------------------------------------------------------ #
        final_result = await compute_full_credibility(
            text_analysis,
            image_analysis,
            video_analysis=video_analysis,
            evidence_results=evidence_results,
            source_url=validated_data.imageUrl or validated_data.videoUrl,
            image_bytes=image_buffer,
        )

        elapsed = round((time.perf_counter() - _start) * 1000)
        print(f"⏱️ Total request time: {elapsed} ms")

        # Expose temporalAnalysis at the top level for convenience
        temporal_analysis = final_result.get("temporalAnalysis", {})

        # ------------------------------------------------------------------ #
        # Step 5: Construct Unified Structured Response (Antigravity restructure)
        # ------------------------------------------------------------------ #
        
        # 1. Credibility Block
        cred_res = {
            "score":     final_result.get("credibility_score", 50),
            "verdict":   final_result.get("verdict", "UNVERIFIED"),
            "riskLevel": final_result.get("risk_level", "medium"),
            "summary":   final_result.get("explanation", "")
        }

        # 2. Text Analysis Block
        # Gather unique sources from all verified claims
        ev_sources = []
        seen_urls = set()
        for res in evidence_results:
            for doc in res.get("evidence", []):
                url = doc.get("url", "")
                if url and url not in seen_urls:
                    seen_urls.add(url)
                    ev_sources.append({
                        "title":  doc.get("title", "Unknown Source"),
                        "source": doc.get("source", doc.get("domain", "unknown")),
                        "url":    url
                    })

        text_res = {
            "score":               text_analysis.get("credibilityScore", 50),
            "verdict":             text_analysis.get("verdict", "Unknown"),
            "primaryClaim":        text_analysis.get("semantic", {}).get("primaryClaim", ""),
            "analysis":            text_analysis.get("explanation", ""),
            "claims":              evidence_results,
            "evidenceSources":     ev_sources,
            "detailedExplanation": final_result.get("explanation", "")
        }

        # 3. Media Analysis Block
        # Prioritize video if present, then image
        media_score = 50
        media_verdict = "Unknown"
        media_analysis_txt = ""
        media_type = "text"
        visual_desc = ""
        media_verification = ""
        
        if validated_data.videoUrl and video_analysis.get("status") == "processed":
            media_type = "video"
            media_score = video_analysis.get("credibilityScore", 50)
            media_verdict = video_analysis.get("verdict", "Medium Risk")
            media_analysis_txt = video_analysis.get("explanation", "")
            visual_desc = video_analysis.get("visualSummary", "")
            media_verification = video_analysis.get("topicSummary", "")
        elif validated_data.imageUrl and image_analysis.get("status") == "processed":
            media_type = "image"
            media_score = image_analysis.get("credibilityScore", 50)
            media_verdict = image_analysis.get("verdict", "High Risk")
            llm_ia = image_analysis.get("llmAnalysis", {})
            media_analysis_txt = llm_ia.get("explanation", "")
            visual_desc = llm_ia.get("imageContent", "")
            media_verification = llm_ia.get("veracityCheck", "")

        media_res = {
            "score":             media_score,
            "verdict":           media_verdict,
            "analysis":          media_analysis_txt,
            "mediaType":         media_type,
            "visualDescription": visual_desc,
            "verification":      media_verification,
            "evidenceSources":   [] # Media specific sources if any
        }

        # 4. AI Probability Block
        ai_score = 0
        ai_verdict = "Unknown"
        ai_analysis = ""
        
        if media_type == "video" and video_analysis.get("status") == "processed":
            ai_det = video_analysis.get("aiDetection", {})
            ai_score = int(ai_det.get("aiGeneratedProbability", 0) * 100)
            ai_verdict = "High Risk" if ai_score > 70 else "Low Risk"
            ai_analysis = ai_det.get("aiReasoning", "No AI artifacts detected.")
        elif media_type == "image" and image_analysis.get("status") == "processed":
            llm_ia = image_analysis.get("llmAnalysis", {})
            ai_score = int(llm_ia.get("aiGeneratedProbability", 0) * 100)
            ai_verdict = normalize_verdict(llm_ia.get("verdict", "Reliable"))
            ai_analysis = llm_ia.get("aiReasoning", "No AI artifacts detected.")

        ai_res = {
            "score":    ai_score,
            "verdict":  ai_verdict,
            "analysis": ai_analysis
        }

        # 5. Metadata Block
        meta_res = {
            "processingTimeMs": elapsed,
            "claimsAnalyzed":   len(deduped_claims),
            "sourcesUsed":      len(seen_urls)
        }

        # 6. Narrative Analysis (Derived for synthesis)
        _populated = [s for s in narrative_summaries if s]
        _campaign_clusters  = [s for s in _populated if s.get("campaign_detected")]
        _high_risk_clusters = [s for s in _populated if s.get("risk_level") == "HIGH"]
        _top_narrative = (
            _campaign_clusters[0] if _campaign_clusters
            else _high_risk_clusters[0] if _high_risk_clusters
            else _populated[0] if _populated
            else {}
        )

        # Build final unified response
        response_data = build_analysis_response(
            cred_res, text_res, media_res, ai_res, meta_res
        )

        # Preserve additional useful fields for debug/compatibility
        response_data["temporalAnalysis"] = temporal_analysis
        response_data["narrativeAnalysis"] = {
            "summary":          _top_narrative,
            "claim_narratives": narrative_summaries,
            "clusters_detected": len({s.get("cluster_id") for s in _populated if s.get("cluster_id")}),
            "campaign_detected": bool(_campaign_clusters),
        }

        # Store the complete results for future identical requests
        if request_hash:
            store_analysis(request_hash, "full", response_data)

        return jsonify(response_data)

    except asyncio.CancelledError:
        elapsed = round((time.perf_counter() - _start) * 1000)
        print(f"🛑 [Job] Analysis cancelled by user after {elapsed} ms (job={job_id})")
        raise

    except Exception as e:
        print(f"❌ Unexpected error: {traceback.format_exc()}")
        return jsonify({"success": False, "message": str(e)}), 500

    finally:
        if job_id:
            job_registry.unregister(job_id)
